version: "3.8"
services:
  selenium-hub:
    image: selenium/hub:4.6.0
    restart: always
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"      
  chrome:
    image: selenium/node-chrome:4.6.0
    restart: always
    container_name: selenium-node-chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
      - SCREEN_DPI=96
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
  firefox:
    image: selenium/node-firefox:4.6.0
    restart: always
    container_name: selenium-node-firefox
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
      - SCREEN_DPI=96
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
  web:
    image: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./config-docker/nginx/html/:/usr/share/nginx/html
    container_name: selenium-test-web-server
